apiVersion: v1
kind: Service
metadata:
  name: {{ include "self-learning.fullname" . }}
  labels:
    {{- include "self-learning.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: 30007
      protocol: TCP
      name: http
  selector:
    {{- include "self-learning.selectorLabels" . | nindent 4 }}
